// ./代表当前目录，../代表双亲目录，/代表根目录
import { cloud , ObjectId,  } from '../../../local-cloud.js'
import type { FunctionContext } from '../../../local-cloud.js'
const { MongoClient } = require('mongodb')
import common from '../utils/common.js'

const db = cloud.mongo.db()

export default async function (ctx: FunctionContext) {

  // 获取当前时间并格式化
  const currentDate = new Date();
  const formattedDate = common.formatDate(currentDate);

  return

  db.collection('iot2_templateUniIOs')
    .insertMany([
      {
        name: '水位传感器',
        templateName: 'WSD',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "4000",
        max_length: 0,
        step: 0,
        unit: "mm",
      },
      {
        name: '水质传感器',
        templateName: 'WQSVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "5000",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '土壤湿度传感器',
        templateName: 'SMSVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "5000",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '水温传感器',
        templateName: 'WT',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "-55",
        max: "125",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '水泵功率百分比',
        templateName: 'WPVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '气泵运行状态',
        templateName: 'APRS',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '水温加热器运行状态',
        templateName: 'WHRS',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '光照传感器',
        templateName: 'ISVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "5000",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '鱼缸灯光功率百分比',
        templateName: 'ALVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '种植灯光功率百分比',
        templateName: 'PGLVR',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '喂食器运行状态',
        templateName: 'FRS',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '空气温度传感器',
        templateName: 'AT',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "50",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '空气湿度传感器',
        templateName: 'AH',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'sensor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '水泵功率百分比控制',
        templateName: 'WPVRC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '气泵控制',
        templateName: 'APRSC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '水温加热器控制',
        templateName: 'WHRSC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '鱼缸灯光功率百分比控制',
        templateName: 'ALVRC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '种植灯光功率百分比控制',
        templateName: 'PGLVRC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "100",
        max_length: 0,
        step: 0,
        unit: "",
      },
      {
        name: '喂食器控制',
        templateName: 'FTC',
        product_id: new ObjectId('67e22c942902516e866abb29'),
        createdAt: formattedDate,
        updateAt: formattedDate,
        type: 'actor',
        data_type: "int",
        enum_list: null,
        min: "0",
        max: "10",
        max_length: 0,
        step: 0,
        unit: "",
      }
    ])

}
